version: '3.8'

services:
  chat-frontend:
    build: . 
    volumes:
      - .:/app
    depends_on:
      - metrics-db
    environment:
      POSTGRES_HOST: "metrics-db"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
    - 8501:8501

  metrics-db:
    image: postgres:13
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "metrics_db"
    ports:
    - 5432:5432

  dashboard:
    image: grafana/grafana:11.0.0
    depends_on:
      - metrics-db
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    ports:
      - "3000:3000"