{
 "title": "User Feedbac",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of User prompts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS human_messages_count\nFROM chat_history\nWHERE message_type = 'user';\n"
    }
   ]
  },
  {
   "title": "Number of feedbacks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(feedback) FROM chat_history LIMIT 50 "
    }
   ]
  },
  {
   "title": "Positive vs negative Feedback",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    feedback, \n    COUNT(*) AS count\nFROM \n    chat_history\nWHERE \n    feedback IN ('thumbs_up', 'thumbs_down')\nGROUP BY \n    feedback;\n"
    }
   ]
  }
 ]
}